// app/contact/page.tsx
import type { NextPage } from "next";
import ContactForm from "../../components/contactForm";
import Header from "../../components/header";

const Contact: NextPage = () => {
  return (
    <div className={"relative overflow-hidden"}>
      <Header
        className={
          "my-10 space-x-36 px-4 md:mx-auto md:flex md:max-w-screen-md md:justify-between md:space-x-20 lg:max-w-screen-lg xl:max-w-screen-xl"
        }
        headertext="Feel free to"
        maintext="Contact Me"
        footertext=""
        image="/Contact.jpg"
        imagealt="Hands typing on a laptop keyboard"
      />
      <div
        className={
          "my-20 px-4 text-white md:mx-auto md:flex md:max-w-screen-md md:justify-between md:px-5 lg:max-w-screen-lg xl:max-w-screen-xl"
        }
      >
        <div className={"mb-5 flex w-full flex-col space-y-4 md:w-1/2 md:pr-5"}>
          <h1
            className={
              "font-heading text-2xl text-white md:text-3xl lg:text-4xl"
            }
          >
            Send Me a Message
          </h1>
          <p
            className={
              "max-w-screen-sm font-body text-sm text-white md:max-w-screen-sm md:text-base lg:max-w-screen-md lg:text-lg xl:max-w-screen-lg"
            }
          >
            Whether you wish to just chat or need to reach me, simply fill out
            this form and I&apos;ll get back to you soon.
          </p>
        </div>
        <ContactForm />
      </div>
    </div>
  );
};

export default Contact;

// src/app/components/contact/contact.component.ts
import { Component } from '@angular/core';
import { Meta, Title } from '@angular/platform-browser';
import { LinkInjectorService } from 'src/app/services/link-injector.service';

import { metaTags } from 'src/app/metaTags';
import { environment } from '../../../environments/environment';

type Message = {
  firstName: string;
  lastName: string;
  email: string;
  messageContent: string;
};

@Component({
  selector: 'app-contact',
  templateUrl: './contact.component.html',
  styleUrls: ['./contact.component.css'],
})
export class ContactComponent {
  message: Message = {
    firstName: '',
    lastName: '',
    email: '',
    messageContent: '',
  };

  confirm = 'hidden';
  button = 'text_gradient mt-2 cursor-pointer rounded-md py-2 font-extrabold';

  turnstileState = 'error';

  environment = environment;
  async resolveKey(event: string | null) {
    this.turnstileState = 'success';

    console.log(`Token received: ${event}`);
    const result = await fetch(`${this.environment.apiurl}/verify-turnstile`, {
      body: JSON.stringify({ token: event }),
      method: 'POST',
      headers: {
        'content-type': 'application/json',
      },
    });

    const outcome = await result.json();
    if (outcome.success) {
      // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
      this.turnstileState = event!;
    } else {
      this.turnstileState = 'error';
    }
  }

  constructor(
    metaService: Meta,
    titleService: Title,
    linkInjector: LinkInjectorService
  ) {
    titleService.setTitle('Contact - Nate Reprogle');
    metaService.addTags(metaTags);

    linkInjector.createLink('canonical', 'https://reprogle.org');
    linkInjector.createLink('preconnect', 'https://fonts.google.com');
    linkInjector.createLink('preconnect', 'https://fonts.gstatic.com', true);
  }

  handleSubmit() {
    switch (this.turnstileState) {
      case 'error': {
        alert('Turnstile verification error. Please refresh and try again');
        break;
      }
      case 'expired': {
        alert('Turnstile verification expired. Please refresh and try again');
        break;
      }
      default: {
        // This will create a webhook to send to Discord. I was going to do email but webhooks were way easier
        const contents = {
          firstName: this.message.firstName,
          lastName: this.message.lastName,
          email: this.message.email,
          message: this.message.messageContent,
        };

        fetch(`${this.environment.apiurl}/discord`, {
          method: 'POST',
          body: JSON.stringify(contents),
          headers: {
            'Content-Type': 'application/json',
          },
        });
        this.confirm = '';
        this.button = 'hidden';
      }
    }
  }
}

<div class="relative overflow-hidden">
  <app-header
    headerText="Feel free to"
    mainText="Contact Me"
    footerText=""
    image="/assets/Contact.jpg"
    imageAlt="Hands typing on a laptop keyboard"
  ></app-header>
  <div
    class="my-20 px-4 text-white md:mx-auto md:flex md:max-w-screen-md md:justify-between md:px-5 lg:max-w-screen-lg xl:max-w-screen-xl"
  >
    <div class="mb-5 flex w-full flex-col space-y-4 md:w-1/2 md:pr-5">
      <h1 class="font-heading text-2xl text-white md:text-3xl lg:text-4xl">
        Send Me a Message
      </h1>
      <p
        class="max-w-screen-sm font-body text-sm text-white md:max-w-screen-sm md:text-base lg:max-w-screen-md lg:text-lg xl:max-w-screen-lg"
      >
        Whether you wish to just chat or need to reach me, simply fill out this
        form and I&apos;ll get back to you soon.
      </p>
    </div>
    <div class="mb-7 block text-white md:flex md:justify-between">
      <form
        (ngSubmit)="handleSubmit()"
        class="flex flex-col items-start"
        ngNativeValidate
      >
        <div>
          <label> Name <span class="text-red-300">*</span></label>
        </div>
        <div class="block w-full md:flex md:justify-between md:space-x-5">
          <div class="mb-5">
            <input
              type="text"
              id="fname"
              name="fname"
              class="w-full rounded-sm p-1 text-black"
              [(ngModel)]="message.firstName"
              placeholder="John"
              required
            />
            <br />
            <label for="fname" class="text-sm"> First </label>
            <br />
          </div>
          <div class="mb-5">
            <input
              type="text"
              id="lname"
              name="lname"
              class="w-full rounded-sm p-1 text-black"
              [(ngModel)]="message.lastName"
              placeholder="Doe"
              required
            />
            <br />
            <label for="lname" class="text-sm"> Last </label>
            <br />
          </div>
        </div>
        <div class="mb-7 w-full">
          <label for="email"> Email <span class="text-red-300">*</span> </label>
          <br />
          <input
            type="email"
            id="email"
            name="email"
            class="w-full rounded-sm p-1 text-black"
            [(ngModel)]="message.email"
            placeholder="john.doe@email.com"
            required
          />
          <br />
        </div>
        <div class="mb-4 w-full">
          <label for="message">
            Message <span class="text-red-300">*</span>
          </label>
          <textarea
            name="message"
            id="message"
            class="w-full rounded-sm p-1 text-black"
            [(ngModel)]="message.messageContent"
            rows="6"
            placeholder="I was hoping to inquire about..."
            required
          ></textarea>
        </div>
        <ngx-turnstile
          [siteKey]="environment.turnstileSiteKey"
          (resolved)="resolveKey($event)"
          theme="dark"
        ></ngx-turnstile>
        <button type="submit" value="Submit" class="{{ button }}">
          SUBMIT
        </button>
        <h1 class="{{ confirm }}">
          Thanks for your message! I&apos;ll be in touch shortly
        </h1>
      </form>
    </div>
  </div>
</div>
