// components/header.tsx
function Header({ ...props }) {
  return (
    <div {...props}>
      <div className="flex flex-col items-start justify-center">
        <h3
          className={"gradient pb-3 font-body text-base font-normal text-white"}
        >
          {{ ...props }.headertext}
        </h3>
        <h1
          className={
            "my-4 font-heading text-5xl font-extrabold leading-none text-white md:whitespace-normal md:text-6xl lg:whitespace-nowrap xl:text-7xl"
          }
        >
          {{ ...props }.maintext}
        </h1>
        <h1
          className={"font-heading text-xl font-normal text-white md:text-2xl"}
        >
          {{ ...props }.footertext}
        </h1>
      </div>
      <picture className={"xl:h-[45%] xl:w-[45%]"}>
        <source srcSet={{ ...props }.image} type="image/jpg" />
        <img
          src={{ ...props }.image}
          alt={{ ...props }.imagealt}
          className={"rounded-full"}
        />
      </picture>
    </div>
  );
}

export default Header;

// src/app/components/header/header.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css'],
})
export class HeaderComponent {
  @Input() headerText = 'Header';
  @Input() mainText = 'Main';
  @Input() footerText = 'Footer';
  @Input() image = 'ImgUrl';
  @Input() imageAlt = 'Image Alt';
}

<div
  class="my-10 space-x-36 px-5 md:mx-auto md:flex md:max-w-screen-md md:justify-between md:space-x-20 lg:max-w-screen-lg xl:max-w-screen-xl"
>
  <div class="flex flex-col items-start justify-center">
    <h3 class="gradient pb-3 font-body text-base font-normal text-white">
      {{ headerText }}
    </h3>
    <h1
      class="my-4 font-heading text-5xl font-extrabold leading-none text-white md:whitespace-normal md:text-6xl lg:whitespace-nowrap xl:text-7xl"
    >
      {{ mainText }}
    </h1>
    <h1 class="font-heading text-xl font-normal text-white md:text-2xl">
      {{ footerText }}
    </h1>
  </div>
  <picture class="xl:h-[45%] xl:w-[45%]">
    <source srcset="{{ image }}" type="image/jpg" />
    <img ngSrc="{{ image }}" alt="{{ imageAlt }}" height="1116" width="1116" class="rounded-full" aria-hidden="true" priority/>
  </picture>
</div>
