// src/app/components/footer/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css'],
})
export class FooterComponent {
  setTwitter(state: boolean) {}

  setInstagram(state: boolean) {}

  getYear(): number {
    return new Date().getFullYear();
  }
}

<!-- This is where the main content goes, so we can center the copyright below it -->
<div class="mb-8 md:flex">
  <div class="mb-5 md:w-2/3">
    <h3 class="font-heading text-xl">
      Living in Arkansas, reaching the world
    </h3>
    <a href="/contact" class="font-heading text-3xl font-bold underline md:text-4xl xl:text-5xl">
      Get in touch
    </a>
  </div>
  <div class="md:w-1/3">
    <h3 class="mb-3 font-heading text-xl md:mb-6">Socials</h3>
    <ul class="space-y-2 text-sm">
      <li>
        <button (click)="setTwitter(true)">
          Twitter
        </button>
        <app-popup trigger={twitter} message="Please note that personal social media sites reflect opinions or beliefs from me, and do not necessarily reflect the beliefs of my current or previous employers. Social media profiles will always adhere to my employers' Code of Ethical and Professional Standards, Non-Discrimination Policy, and Employee Confidentiality Agreement." setTrigger={setTwitter} redirectTitle="Twitter" redirectLink="https://www.twitter.com/natereprogle" redirectTime={7} />
      </li>
      <li>
        <a href="https://www.linkedin.com/in/natereprogle/">
          LinkedIn
        </a>
      </li>
      <li>
        <button (click)="setInstagram(true)">Instagram</button>
        <app-popup trigger={instagram} message="Please note that personal social media sites reflect opinions or beliefs from me, and do not necessarily reflect the beliefs of my current or previous employers. Social media profiles will always adhere to my employers' Code of Ethical and Professional Standards, Non-Discrimination Policy, and Employee Confidentiality Agreement." setTrigger={setInstagram} redirectTitle="Instagram" redirectLink="https://www.instagram.com/natereprogle" redirectTime={7} />
      </li>
      <li>
        <a href="https://www.github.com/TerrrorByte">GitHub</a>
      </li>
    </ul>
  </div>
</div>
<!--  Copyright -->
<div class="flex flex-col items-center justify-center text-xs">
  <h2>Copyright © 2022-{{getYear()}} | Nate Reprogle</h2>
  <p>
    Site source:
    <a href="https://www.github.com/TerrrorByte/reprogle.org" class="hover:underline">
      click here
    </a>
  </p>
</div>

// components/footer.tsx
"use client";
import Link from "next/link";
import Popup from "./popup";
import { useState } from "react";
import { Transition } from "@headlessui/react";

export default function Footer({ ...props }) {
  const [instagram, setInstagram] = useState(false);
  const [twitter, setTwitter] = useState(false);

  return (
    <div {...props}>
      {/* This is where the main content goes, so we can center the copyright below it */}
      <div className={"mb-8 md:flex"}>
        <div className={"mb-5 md:w-2/3"}>
          <h3 className={"font-heading text-xl"}>
            Living in Arkansas, reaching the world
          </h3>
          <Link
            href="/contact"
            className={
              "font-heading text-3xl font-bold underline md:text-4xl xl:text-5xl"
            }
          >
            Get in touch
          </Link>
        </div>
        <div className={"md:w-1/3"}>
          <h3 className={"mb-3 font-heading text-xl md:mb-6"}>Socials</h3>
          <ul className={"space-y-2 text-sm"}>
            <li>
              <button
                onClick={() => {
                  setTwitter(true);
                }}
              >
                Twitter
              </button>
              <Transition
                show={twitter}
                enter="transition-all duration-300"
                enterFrom="opacity-0"
                enterTo="opacity-100"
                leave="transition-opacity duration-300"
                leaveFrom="opacity-100"
                leaveTo="opacity-0"
              >
                <Popup
                  trigger={twitter}
                  message={
                    "Please note that personal social media sites reflect opinions or beliefs from me, and do not necessarily reflect the beliefs of my current or previous employers. Social media profiles will always adhere to my employers' Code of Ethical and Professional Standards, Non-Discrimination Policy, and Employee Confidentiality Agreement."
                  }
                  setTrigger={setTwitter}
                  redirectTitle={"Twitter"}
                  redirectLink={"https://reprogle.org/twitter"}
                  redirectTime={7}
                />
              </Transition>
            </li>
            <li>
              <Link href="https://www.linkedin.com/in/natereprogle/">
                LinkedIn
              </Link>
            </li>
            <li>
              <button onClick={() => setInstagram(true)}>Instagram</button>
              <Transition
                show={instagram}
                enter="transition-all duration-300"
                enterFrom="opacity-0"
                enterTo="opacity-100"
                leave="transition-opacity duration-300"
                leaveFrom="opacity-100"
                leaveTo="opacity-0"
              >
                <Popup
                  trigger={instagram}
                  message={
                    "Please note that personal social media sites reflect opinions or beliefs from me, and do not necessarily reflect the beliefs of my current or previous employers. Social media profiles will always adhere to my employers' Code of Ethical and Professional Standards, Non-Discrimination Policy, and Employee Confidentiality Agreement."
                  }
                  setTrigger={setInstagram}
                  redirectTitle={"Instagram"}
                  redirectLink={"https://reprogle.org/instagram"}
                  redirectTime={7}
                />
              </Transition>
            </li>
            <li>
              <Link href="https://www.github.com/TerrrorByte">GitHub</Link>
            </li>
          </ul>
        </div>
      </div>
      {/* Copyright */}
      <div className="flex flex-col items-center justify-center text-xs">
        <h2>Copyright © 2022-{new Date().getFullYear()} | Nate Reprogle</h2>
        <p>
          Site source:{" "}
          <Link
            href="https://www.github.com/TerrrorByte/reprogle.org"
            className="hover:underline"
          >
            click here
          </Link>
        </p>
      </div>
    </div>
  );
}
