// src/app/components/resume-item/resume-item.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-resume-item',
  templateUrl: './resume-item.component.html',
  styleUrls: ['./resume-item.component.css'],
})
export class ResumeItemComponent {
  @Input() timeRange: string = 'Time Range';
  @Input() company: string = 'Company';
  @Input() title: string = 'Title';
  @Input() description: string = 'Description';
}

<div class="mb-7 block lg:flex lg:justify-between lg:space-x-5">
  <div class="flex flex-col lg:w-1/3 lg:space-y-2">
    <h1 class="font-bold">{{ timeRange }}</h1>
    <h2>{{ company }}</h2>
  </div>
  <div class="flex flex-col lg:w-3/4 lg:space-y-2">
    <h1 class="text_gradient text-2xl font-extrabold">{{ title }}</h1>
    <p>{{ description }}</p>
  </div>
</div>

// components/resumeItem.tsx
function ResumeItem({ ...props }) {
  return (
    <div className={"mb-7 block lg:flex lg:justify-between lg:space-x-5"}>
      <div className={"flex flex-col lg:w-1/3 lg:space-y-2"}>
        <h1 className={"font-bold"}>{{ ...props }.timeRange}</h1>
        <h2>{{ ...props }.company}</h2>
      </div>
      <div className={"flex flex-col lg:w-3/4 lg:space-y-2"}>
        <h1 className={"text_gradient text-2xl font-extrabold"}>
          {{ ...props }.title}
        </h1>
        <p>{{ ...props }.description}</p>
      </div>
    </div>
  );
}

export default ResumeItem;
